### ISSUE TITLE
Link Preview not working

### ISSUE THREAD

**Issue by rushbhshah1110** [LeonardoCardoso/Facebook-Link-Preview#15]
Hi,
thank you for your script but i am having issue with your code.
I dont know why but it is not working on my server.
I have downloaded your sample and hosted on my server but it is not working.
Here is url of my application.Please help me out ASAP.

http://144.76.184.38:2000/Facebook-Link-Preview-master/

NOTE : i don't need to store it to database so i have not setup DB in this sample.
i just want to have preview of link.

**Comment by dieterdeweirdt** [comment]
I seem to have the same problem... On my local computer this works fine. On the server it works for certain websites but not for all... (facebook, flickr, twitter, ... doesn't work)

**Comment by LeonardoCardoso** [comment]
Transferred to https://github.com/LeonardoCardoso/Link-Preview/issues/5
