### ISSUE TITLE
FaceBook Pull

### ISSUE THREAD

**Issue by wxflint** [LeonardoCardoso/Facebook-Link-Preview#16]
Hello Just want to say Awesome job on the script,
I have one issue do you know why it does not pull the data from a Facebook Page or Profile page?
Always Returns: "Content Not Found | Facebook"
![notfound](https://cloud.githubusercontent.com/assets/1435118/5540593/49483aa0-8a9b-11e4-979c-5c1c4e7f2c94.JPG)

**Comment by LeonardoCardoso** [comment]
Well, is it localhost?! Because I just checked on my website and it works...
![screen shot 2015-01-03 at 23 58 38](https://cloud.githubusercontent.com/assets/1775157/5604200/952dc00e-93a4-11e4-90b8-937710e2e482.png)
![screen shot 2015-01-03 at 23 57 16](https://cloud.githubusercontent.com/assets/1775157/5604201/95adeaf4-93a4-11e4-9886-4af595942805.png)

**Comment by wxflint** [comment]
Try this one. https://facebook.com/patrick.sauer

**Comment by wxflint** [comment]
And I am using it on a hosted server. Not local host.

**Comment by LeonardoCardoso** [comment]
I know what is your profile: https://www.facebook.com/patrick.sauer
i just put it on my browser and this is what I've got.

![screen shot 2015-01-04 at 00 24 59](https://cloud.githubusercontent.com/assets/1775157/5604244/37f90fd4-93a8-11e4-8f96-c8c4bf37fd14.png)

**Comment by LeonardoCardoso** [comment]
Maybe it's just some privacy issues on your account, @wxflint.

**Comment by wxflint** [comment]
Yeah I will have to do some more testing. Thanks. 
Do you have any plans to do an admin panel to delete abusive posts?

**Comment by LeonardoCardoso** [comment]
@wxflint What kind of abusive posts?!

**Comment by wxflint** [comment]
Let's say I use the script on my site. And somebody posts Pornography links on there how does one go about removing that post.

**Comment by wxflint** [comment]
http://kingsport411.com/facelink/

**Comment by LeonardoCardoso** [comment]
On my website no content is saved on database. Should you do on yours, you must manage this. @wxflint

**Comment by wxflint** [comment]
Check this out. http://kingsport411.com/facelink/admin/

**Comment by LeonardoCardoso** [comment]
Nice, @wxflint. It's a great deal.
