### ISSUE TITLE
URL Incomplete

### ISSUE THREAD

**Issue by nicemen** [LeonardoCardoso/Facebook-Link-Preview#18]
Hi, i have problem with Regex !
I post url : http://www.site.com/us/modules/news/index.php?cid=30&lid=1654
& Result after post 
http://www.site.com/us/modules/news/index.php?cid=30
Help me please, Thank !

**Comment by LeonardoCardoso** [comment]
That's because both are redirected to http://www.salesforce.com/platform/overview/?d=70130000000liBh
