### ISSUE TITLE
Problem with russian encoding

### ISSUE THREAD

**Issue by AlejandroDelRioAlbrechet** [LeonardoCardoso/Facebook-Link-Preview#20]
Hi I have found one problem with php encoding

try to paste this url to your preview

http://finance.i.ua/

You will see unreadable strings.

**Comment by LeonardoCardoso** [comment]
I'll check it out.

**Comment by AlejandroDelRioAlbrechet** [comment]
Hi I have fixed this issue by adjusting one line in Content.php in function getMetaTagsEncoding 
this line @$doc->loadHTML($contents);  should become @$doc->loadHTML( mb_convert_encoding( $contents, 'HTML-ENTITIES', 'UTF-8' ) );

If you accept pull request I can push it

**Comment by LeonardoCardoso** [comment]
Please, do it. I'll test it!

**Comment by LeonardoCardoso** [comment]
I've tested and this was the result... What was yours?!

![screen shot 2015-03-28 at 13 59 37](https://cloud.githubusercontent.com/assets/1775157/6881332/bced6dc0-d552-11e4-939c-79d7d0dc910d.png)

**Comment by AlejandroDelRioAlbrechet** [comment]
Yes that is correct.

**Comment by clicman** [comment]
I`m using outdated version of project in my trivate repo so I just leave my solution here:

    $encoding = 'unknown';
    /*...*/
    //This if works on youtube
    if ($meta->getAttribute('charset')) {
                    $encoding = strtolower($meta->getAttribute('charset'));
    //This is useful for htttp://ya.ru
    } else if (strtolower($meta->getAttribute('http-equiv')) === "content-type") {
                    $content = strtolower($meta->getAttribute('content'));
                    if (strpos($content, "charset=") !== FALSE) {
                        $encoding = trim(explode(";", explode("charset=", $content)[1])[0]);
                    }
    }
    
    //Then use it like:
      if ($encoding === "unknown") {
                //If unnown try to get it as unicode
                $metaTags["title"] = utf8_decode($metaTags["title"]);
                $metaTags["description"] = utf8_decode($metaTags["description"]);
            } else {
                //Convert encoding
                $metaTags["title"] = mb_convert_encoding($metaTags["title"], $encoding);
                $metaTags["description"] = mb_convert_encoding($metaTags["description"], $encoding);
      }

Passed sites are: 
* http://ya.ru
* https://facebook.com
* http://www.youtube.com/watch?v=jsO1nT5tUX0
* http://finance.i.ua/

**Comment by LeonardoCardoso** [comment]
Thanks, @clicman!

**Comment by LeonardoCardoso** [comment]
Using @$doc->loadHTML('<?xml encoding="UTF-8">', $contents); works as well.

**Comment by moneytoo** [comment]
Encoding is also broken for me in link such as ``https://www.youtube.com/watch?t=1&v=ovaVOmVmFZs`` - it's HTML5 page (``<!DOCTYPE html>`` which utilizes UTF-8 by default) and encoding is also specified in HTTP header (``Content-Type: text/html; charset=utf-8``).

**Comment by LeonardoCardoso** [comment]
Transferred to https://github.com/LeonardoCardoso/Link-Preview/issues/4
