### ISSUE TITLE
Unable to Preview some site

### ISSUE THREAD

**Issue by bangar** [LeonardoCardoso/Facebook-Link-Preview#21]
Hi,

     We unable to preview some sites can you please check everyone facing same issue.
 Ex : http://www.microsoft.com  here no images are displaying.

**Comment by LeonardoCardoso** [comment]
I'l check it out as soon as I can.

**Comment by LeonardoCardoso** [comment]
Fixed on 5848978c7664b874cf2be5975bc29fdfa0c27b34
