### ISSUE TITLE
https urls not working in link preview

### ISSUE THREAD

**Issue by bangar** [LeonardoCardoso/Facebook-Link-Preview#22]
Hi,

           We are facing issue with https urls can you please what's the problem. We download files from Git and create a site and copied all in there without any changes in code. Here everything working fine but when we enter https url for image preview here images are not displaying.

Please visit following link http://www.ftpchat.com and type http or https://www.facebook.com here no images are displaying. For non https url working without any issue.

**Comment by LeonardoCardoso** [comment]
Is your version up to date?! Because I've improved the recognition of images is last commit. I've tested im my machine and it works ok.

![screen shot 2015-04-17 at 17 37 01](https://cloud.githubusercontent.com/assets/1775157/7206383/be9c04ca-e528-11e4-942e-c2b04a6f4850.png)
![screen shot 2015-04-17 at 17 37 32](https://cloud.githubusercontent.com/assets/1775157/7206382/be9a5aee-e528-11e4-97eb-1ead11dff42e.png)

**Comment by bangar** [comment]
Yeah it's working in your site but not working in our server. We using IIS 8.5 and Server 2012 is there any changes we need to add ??

**Comment by LeonardoCardoso** [comment]
About server configurations I can't tell.

On Friday, April 17, 2015, bangar <notifications@github.com> wrote:

> Yeah it's working in your site but not working in our server. We using IIS
> 8.5 and Server 2012 is there any changes we need to add ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeonardoCardoso/Facebook-Link-Preview/issues/22#issuecomment-94025359>
> .
>


-- 
*Leonardo Cardoso*
leocardz.com

**Comment by bangar** [comment]
Leonardo There is no issues with server, i am just asking this support all OS or only Linux. If all OS need to find out the issue because even 1 line of character code also we didn't changed. I am .Net developer having trouble to debug  :) the issue

**Comment by LeonardoCardoso** [comment]
Which PHP and Apache versions are yours?!

**Comment by bangar** [comment]
PHP 5.6.0 with IIS 8.5 with following extensions enabled and disabled. 

![php](https://cloud.githubusercontent.com/assets/4168947/7206841/f9911096-e552-11e4-961a-866fbaab7614.jpg)

**Comment by LeonardoCardoso** [comment]
I don't know if there's a compatibility issue with IIS. I gotta test it.

**Comment by bangar** [comment]
thank you Leo Can you please check and update what's the issue

**Comment by aerandir92** [comment]
I have similar issue, PHP 5.6 on apache server.
I have several links that works fine on your site, but not on your test when I just download your code from here
https://www.komplett.no/asus-zenbook-ux303ln-133-full-hd-matt/832804  is an example link
No links from komplett.no works on the version a downloaded just now from Github, but it works fine on your webiste. 
I tried your first version (first commit), it worked better there

**Comment by LeonardoCardoso** [comment]
This must be some configuration issue we are missing. I just tried your url in my local machine and it works.

![screen shot 2015-04-30 at 11 52 58](https://cloud.githubusercontent.com/assets/1775157/7411382/7f64da14-ef2f-11e4-92d6-6cd55fa1a3cc.png)

**Comment by aerandir92** [comment]
That's weird. That is your code downloaded from Github, untouched?
Could it be some problem with PHP or Curl version?

**Comment by LeonardoCardoso** [comment]
Yes it is. 

My machine:
```
$ php -v
PHP 5.5.20 (cli) (built: Feb 25 2015 23:30:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

$ apachectl -v
Server version: Apache/2.4.10 (Unix)
Server built:   Jan  8 2015 20:48:33

CURL_VERSION_IPV6, CURL_VERSION_SSL, CURL_VERSION_LIBZ

Server:
```
$ php -v
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

$ apache2 -v
Server version: Apache/2.4.7 (Unix)
Server built:   Jul 22 2014 14:36:38

CURL_VERSION_IPV6, CURL_VERSION_SSL, CURL_VERSION_LIBZ
```

**Comment by aerandir92** [comment]
Høh, komplett.no links works in my server, just not locally

Server:
PHP Version	5.6.8
cURL Information	7.36.0
Apache Version	2.4.12

Locally:
Apache Version	2.4.10 (Win32) OpenSSL/1.0.1i
PHP Version      5.6.3
cURL Information	7.36.0

Oh well, as long as it works on the server I'm happy
