### ISSUE TITLE
Not Save Post

### ISSUE THREAD

**Issue by ayosearch** [LeonardoCardoso/Facebook-Link-Preview#25]
Hii all,

I try http://ping.ayosearch.com/Facebook-Link-Preview-master/

function not work and not insert Mysql, please help me how source not wok my server

**Comment by LeonardoCardoso** [comment]
Check your database credentials.

On Sunday, May 10, 2015, ayosearch <notifications@github.com> wrote:

> Hii all,
>
> I try http://ping.ayosearch.com/Facebook-Link-Preview-master/
>
> function not work and not insert Mysql, please help me how source not wok
> my server
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeonardoCardoso/Facebook-Link-Preview/issues/25>.
>


-- 
*Leonardo Cardoso*
leocardz.com

<http://git.io/vfgvV>

**Comment by LeonardoCardoso** [comment]
Check your database credentials.
To custom your database configurations, you just need to change the following values in [php/classes/Database.php](https://github.com/LeonardoCardoso/Facebook-Link-Preview/blob/master/php/classes/Database.php)

```
$host = "localhost";
$user = "";
$password = "";
$database = "linkpreview";
```

Make sure your columns are the same as those ones in [linkpreview.sql](https://github.com/LeonardoCardoso/Facebook-Link-Preview/blob/master/linkpreview.sql).
