### ISSUE TITLE
noThumbAction function runs twice in linkPreview.js when clicking noThumb checkbox

### ISSUE THREAD

**Issue by Yongjiwang** [LeonardoCardoso/Facebook-Link-Preview#26]
when clicking noThumb checkbox, its click event fires.
In the same time the click event of the noThumb checkbox parent: noThumbDiv fires too.
It cause the thumbnail still show up and the preview content doesn't change.
Please check it out.
Thanks.

**Comment by LeonardoCardoso** [comment]
Actually what was happening was when clicking in noThumb_ the value change happens before it reaches noThumbAction(). And that causes the value to be changed back again.

**Comment by Yongjiwang** [comment]
Good job. :)
