### ISSUE TITLE
plugin function URL with reciprocal link

### ISSUE THREAD

**Issue by ayosearch** [LeonardoCardoso/Facebook-Link-Preview#29]
reciprocal link

**Comment by LeonardoCardoso** [comment]
Is that about Facebook Link Preview?

**Comment by ayosearch** [comment]
yes ,leo sorry, I think will put on my web user to create a link exchange 
if you do not mind giving advice to plugin  "Facebook-Link-Preview"


<?php
$mydomain = "http://example.com/"; // Set this to your domain
$myurl = "$url"; // url post
 $urls = explode ("\n", $myurl);

echo "<B>Checking back links to $mydomain....</B><P><FONT SIZE=-1>";

foreach ($urls as $url) {
if (strlen ($url)) {
echo $url . "<B><FONT COLOR=";
if (strpos (file_get_contents($url), $mydomain) != FALSE) {
echo "GREEN> Found insert database";
} else {
echo "RED> Missing post not inset database ";
}
echo "</FONT></B><BR>";
}
}
echo "</FONT>";
?>

**Comment by LeonardoCardoso** [comment]
Sorry, but I'm really trying to understand what's your point.
