### ISSUE TITLE
Diacritics problem

### ISSUE THREAD

**Issue by henrydeguzman** [LeonardoCardoso/Facebook-Link-Preview#31]
There is a problem with diacritics. its 70% working in localhost but in live. 0% working. 

try these two links
http://www.neocanal.com/blog/7-reflexes-adopter-virage-digital-reussi-dirigeant?utm_campaign=d%C3%A9veloppeur

http://jm.prive.pagesperso-orange.fr/docpro/La_dem_securite.htm

**Comment by henrydeguzman** [comment]
I've just corrected you're code. As i expected there is a problem in getMetaTagsEncoding function in Content.php you've just pass a argument version and encoding into a newly initialized domdocument which is not actually necessary. you should pass the charset encoding when the dom is loaded "$doc->loadHTML('<?xml encoding="UTF-8">', .$contents);

**Comment by LeonardoCardoso** [comment]
Can you just create a pull request with your fix?!
