### ISSUE TITLE
Angularjs + Bootstrap Version

### ISSUE THREAD

**Issue by LeonardoCardoso** [LeonardoCardoso/Facebook-Link-Preview#36]
TO-DO

**Comment by moneytoo** [comment]
To be able to parse Angularjs OG data? Sometimes setting ``facebookexternalhit...`` UA is enough (trying to parse something like https://www.stream.cz/praha-vs-prachy/10007538-smenarny-trailer)..

**Comment by LeonardoCardoso** [comment]
@moneytoo Not all websites have OG data.

**Comment by LeonardoCardoso** [comment]
New repository https://github.com/LeonardoCardoso/Link-Preview
