### ISSUE TITLE
Not getting proper preview of URL

### ISSUE THREAD

**Issue by mbarwick83** [LeonardoCardoso/Facebook-Link-Preview#37]
If I don't include http:// (or https)...the URL preview data is strange and off - and won't pick up images. Looks like this. 

I know you're not monitoring this package, but I'm building a Laravel Package for this and would love to get it to work. I could share it with you (more options! :boom:)

<img width="539" alt="screen shot 2015-11-06 at 4 53 28 am" src="https://cloud.githubusercontent.com/assets/330011/10994183/a5a3b6ac-8442-11e5-9cbe-6aa4fcdc351f.png">

<img width="530" alt="screen shot 2015-11-06 at 4 56 17 am" src="https://cloud.githubusercontent.com/assets/330011/10994189/c3d2309a-8442-11e5-8104-ad9643838229.png">

**Comment by LeonardoCardoso** [comment]
I fix that on the new [Link Preview](http://lab.leocardz.com/link-preview/). Please, consider on using the new Link Preview. It's way better than the old one and more flexible and customizable.

![http://i.imgur.com/zzKekjR.png](http://i.imgur.com/zzKekjR.png)

**Comment by mbarwick83** [comment]
As mentioned, I'm build a package for Laravel, can't use AngularJS. Is it a somewhat quick fix?

**Comment by LeonardoCardoso** [comment]
I'll check it out and post the solution here.

**Comment by mbarwick83** [comment]
@LeonardoCardoso Yeah, I just looked at the source. Totally doable. Much of the PHP is the same (Structure), so no biggie. Thanks man. New angularJS version looks legit :facepunch:

**Comment by LeonardoCardoso** [comment]
👊😂
